# Generated by Django 3.1.4 on 2021-01-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
