# Generated by Django 3.1.4 on 2021-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'secondary'), ('P', 'primary'), ('D', 'danger')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, choices=[('B', 'Best Seller'), ('N', 'NEW'), ('O', 'Discount')], max_length=1),
        ),
    ]
