# Generated by Django 3.1.4 on 2021-01-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='nigeria', max_length=100),
            preserve_default=False,
        ),
    ]
